### ISSUE TITLE
Location extension schema_usecase_2.json patch produces invalid extended OCDS schema file

### ISSUE THREAD

**Issue by mpostelnicu** [open-contracting/implementation-and-extensions#10]
Running JSON schema syntax validation on the patched schema will result in:

```
{
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : "/definitions/Item/properties/deliveryLocation/properties/gazetteer/properties/identifiers/items/0"
  },
  "domain" : "syntax",
  "message" : "JSON value is of type string, not a JSON Schema (expected an object)",
  "found" : "string"
}, {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : "/definitions/Item/properties/deliveryLocation/properties/gazetteer/properties/identifiers/items/1"
  },
  "domain" : "syntax",
  "message" : "JSON value is of type string, not a JSON Schema (expected an object)",
  "found" : "string"
}
```

**Comment by timgdavies** [comment]
Thanks for pointing to this. Will investigate and check out the fix.

**Comment by kindly** [comment]
@mpostelnicu thanks for this!

We are in the process of changing the way we define extensions.  The details can be found
https://github.com/open-contracting/standard_extension_template

@Bjwebb has already started converting this extension to the new format and found that issue too!
https://github.com/Bjwebb/proposed_location_extension/commit/abfd290e26e4b806c54174c9fd21e398b08ab4b2
