### ISSUE TITLE
Kenya IFMIS/OCDS update

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/implementation-and-extensions#12]
I was reading the [OGP commitments for Kenya](http://www.opengovpartnership.org/sites/default/files/Kenya_AP2_2016_0.pdf) (because that's what i like to do in my free time!  *cough joking* :stuck_out_tongue_winking_eye:)

I noticed that in February, the mapping of their system to OCDS should be done... and in June they would have a new portal ready.

Do you have any idea on who is executing that project? I will be working with a team on a project related to PPP OCDS extension and it would be great if we can plan ahead a feature for integrating between PPP Disclosure and the rest of the contracting processes.

So any details/contact info about that would be appreciated... please feel free to reply to my private email (mraad [@] worldbank.org)

thanks a ton.

**Comment by timgdavies** [comment]
Good questions. Will reply via the helpdesk from data@open-contracting.org shortly.
