### ISSUE TITLE
Extended list of procurement methods

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/implementation-and-extensions#2]
From @mikaelmh:

> How do we include our specific classifications for how contracts are awarded? (What we call ‘SelectionMethod’ and ‘SpecialCaseReason’ but I think you call ‘procurementMethod’ and ‘procurementMethodRationale’ respectively.
> 
> You can see the list of values here: https://docs.google.com/spreadsheets/d/1eNg5hiNGE375-xpAk2KFw9B12pVv-Ss--rjDJCbuOVM/edit#gid=853230437 

At the moment `procurementMethod` is a closed codelist, with values for open, selective and limited. 

Any implementation should attempt to map the classifications of contract awards to this codelist - as knowing when things are open, selective or limited is important to many users.

It looks to me like `SpecialCaseReason` would map directly to `procurementMethodRationale`.

But this does leave your more detailed `selectionMethod` in need of a property. Adding `procurementMethodDetails` would seem like a natural property for us to propose alongside `awardMethodDetails`. 

Again - we could work this up as an extension for the moment, but I think this is the kind of thing that could be proposed as a solid proposal for the next upgrade of the standard.

**Comment by jpmckinney** [comment]
Seems closed by linked issue.
