### ISSUE TITLE
National vs International procedures

### ISSUE THREAD

**Issue by olafveerman** [open-contracting/implementation-and-extensions#3]
Is there a field that describes whether a tender is national or international?

**Comment by timgdavies** [comment]
We don't have an explicit flag for this right now. 

The proposed [Location Extension](https://github.com/open-contracting/implementation-and-extensions/blob/master/proposed_extensions/proposed_location/schema_usecase_2.json) which will be brought forward as a proposal for revising the standard soon might be the best way to capture this right now.

Essentially, it attaches a 'deliveryLocation' to line items, which can use both point locations, and gazeteer entries, including country codes. 

So, for example, to indicate that a contract is for work to be delivered in Nepal, a block of line-item information might look like this:

``` json
{ "items": [
                    {
                        "id": 1, 
                        "description": "'Building Cleaning Services.'", 
                        "classification": {
                            "scheme": "CPV", 
                            "id": "90911200", 
                            "uri": "http://purl.org/cpv/2008/code-90911200", 
                            "description": "Building-cleaning services"
                        }, 
                        "deliveryLocation":{
                            "description":"Nepal",
                            "gazeteer":{
                                "scheme":"ISO2",
                                "identifiers":["NP"]
                            }
                        }
                    }
            ]
}
```

Would this capture what you need? I realise it is pretty deeply nested down in the tree - so it might be that we need to consider something higher level.

Can you give an example use case of what you are trying to model?

**Comment by olafveerman** [comment]
Hi @timgdavies 
The delivery location is great and we're planning on using it.

The national / international field refers to whether a tender is open to international companies, or only available to national ones. I guess it would be closely related to `selectionDetails` and `procurementMethod`.
Would you store this under `eligibilityCriteria`?

**Comment by timgdavies** [comment]
@olafveerman Yep - it definitely looks like it would be well suited to going under `eligibilityCriteria` if unstructured information is enough for your use case.
