### ISSUE TITLE
Look at Ukranian Zovnishtorgvydav XML

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/implementation-and-extensions#4]
This could possibly involve a sample mapping.

Data is at ftp://213.156.91.123/EDZ_DATA_EXPORT/ with more information in Ukrainian at https://tender.me.gov.ua/EDZFrontOffice/menu/en/announcement_detail?id=EDZrDW4DJ5

I think I remember that this data is coming out of an Oracle database, so this may be something to investigate in terms of Oracle's interest in OCDS.

**Comment by LindseyAM** [comment]
I think this mapping should be a priority but good to confirm with @myroslav

**Comment by myroslav** [comment]
I should have first iteration of OCDS release that ZTV team produced from that data next week.

**Comment by timgdavies** [comment]
That's fantastic. Feel free to send it over and we'd be happy to sort out some feedback / comments if that would be useful.

**Comment by jpmckinney** [comment]
Closing as it's unclear whether there is still an issue to resolve.
