### ISSUE TITLE
Prozorro only produces "records"

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/implementation-and-extensions#5]
At the moment, the Prozorro api at https://api.openprocurement.org/api/ only produces the latest snapshot of a data.

@myroslav Is there a timeline for when Prozorro will be producing historical releases?

**Comment by LindseyAM** [comment]
Just to be clear, my understanding is that the goal is to have the different chronological 'releases' to ensure the versioned history is preserved should information change overtime.

**Comment by myroslav** [comment]
We have very detailed history of all changes of every record (internally stored as JSON patch), and to produce proper OCDS releases, we'd have to take into consideration merge strategies for every patch to put just enough information for merging to work properly.

I.e. in case we have only single property of "replace" structure, we'd have to put whole structure in release for the strategy to work properly during merge.

Separate logic will apply to document collections to expose change history. I'm not sure we'll need that history in merged record.

And yes, we do want to have OCDS releases reconstructed.
